export const STATE_DATA_JSON = [
  { id: 1, name: 'Andaman and Nicobar (AN)' },
  { id: 2, name: 'Andhra Pradesh (AP)' },
  { id: 3, name: 'Arunachal Pradesh (AR)' },
  { id: 4, name: 'Assam (AS)' },
  { id: 5, name: 'Bihar (BR)' },
  { id: 6, name: 'Chandigarh (CH)' },
  { id: 7, name: 'Chhattisgarh (CG)' },
  { id: 8, name: 'Dadra and Nagar Haveli (DN)' },
  { id: 9, name: 'Daman and Diu (DD)' },
  { id: 10, name: 'Delhi (DL)' },
  { id: 11, name: 'Goa (GA)' },
  { id: 12, name: 'Gujarat (GJ)' },
  { id: 13, name: 'Haryana (HR)' },
  { id: 14, name: 'Himachal Pradesh (HP)' },
  { id: 15, name: 'Jammu and Kashmir (JK)' },
  { id: 16, name: 'Jharkhand (JH)' },
  { id: 17, name: 'Karnataka (KA)' },
  { id: 18, name: 'Kerala (KL)' },
  { id: 19, name: 'Lakshdweep (LD)' },
  { id: 20, name: 'Madhya Pradesh (MP)' },
  { id: 21, name: 'Maharashtra (MH)' },
  { id: 22, name: 'Manipur (MN)' },
  { id: 23, name: 'Meghalaya (ML)' },
  { id: 24, name: 'Mizoram (MZ)' },
  { id: 25, name: 'Nagaland (NL)' },
  { id: 26, name: 'Odisha (OD)' },
  { id: 27, name: 'Puducherry (PY)' },
  { id: 28, name: 'Punjab (PB)' },
  { id: 29, name: 'Rajasthan (RJ)' },
  { id: 30, name: 'Sikkim (SK)' },
  { id: 31, name: 'Tamil Nadu (TN)' },
  { id: 32, name: 'Tripura (TR)' },
  { id: 33, name: 'Uttar Pradesh (UP)' },
  { id: 34, name: 'Uttarakhand (UK)' },
  { id: 35, name: 'West Bengal (WB)' },
]

export const COUNTRY_DATA_JSON = [
  {
    id: 1,
    code: 'AFG',
    name: 'Afghanistan',
    alpha2Code: 'AF',
  },
  {
    id: 2,
    code: 'ALA',
    name: 'Åland',
    alpha2Code: 'AX',
  },
  {
    id: 3,
    code: 'ALB',
    name: 'Albania',
    alpha2Code: 'AL',
  },
  {
    id: 4,
    code: 'DZA',
    name: 'Algeria',
    alpha2Code: 'DZ',
  },
  {
    id: 5,
    code: 'ASM',
    name: 'American Samoa',
    alpha2Code: 'AS',
  },
  {
    id: 6,
    code: 'AND',
    name: 'Andorra',
    alpha2Code: 'AD',
  },
  {
    id: 7,
    code: 'AGO',
    name: 'Angola',
    alpha2Code: 'AO',
  },
  {
    id: 8,
    code: 'AIA',
    name: 'Anguilla',
    alpha2Code: 'AI',
  },
  {
    id: 9,
    code: 'ATA',
    name: 'Antarctica',
    alpha2Code: 'AQ',
  },
  {
    id: 10,
    code: 'ATG',
    name: 'Antigua and Barbuda',
    alpha2Code: 'AG',
  },
  {
    id: 11,
    code: 'ARG',
    name: 'Argentina',
    alpha2Code: 'AR',
  },
  {
    id: 12,
    code: 'ARM',
    name: 'Armenia',
    alpha2Code: 'AM',
  },
  {
    id: 13,
    code: 'ABW',
    name: 'Aruba',
    alpha2Code: 'AW',
  },
  {
    id: 14,
    code: 'AUS',
    name: 'Australia',
    alpha2Code: 'AU',
  },
  {
    id: 15,
    code: 'AUT',
    name: 'Austria',
    alpha2Code: 'AT',
  },
  {
    id: 16,
    code: 'AZE',
    name: 'Azerbaijan',
    alpha2Code: 'AZ',
  },
  {
    id: 17,
    code: 'BHS',
    name: 'Bahamas',
    alpha2Code: 'BS',
  },
  {
    id: 18,
    code: 'BHR',
    name: 'Bahrain',
    alpha2Code: 'BH',
  },
  {
    id: 19,
    code: 'BGD',
    name: 'Bangladesh',
    alpha2Code: 'BD',
  },
  {
    id: 20,
    code: 'BRB',
    name: 'Barbados',
    alpha2Code: 'BB',
  },
  {
    id: 21,
    code: 'BLR',
    name: 'Belarus',
    alpha2Code: 'BY',
  },
  {
    id: 22,
    code: 'BEL',
    name: 'Belgium',
    alpha2Code: 'BE',
  },
  {
    id: 23,
    code: 'BLZ',
    name: 'Belize',
    alpha2Code: 'BZ',
  },
  {
    id: 24,
    code: 'BEN',
    name: 'Benin',
    alpha2Code: 'BJ',
  },
  {
    id: 25,
    code: 'BMU',
    name: 'Bermuda',
    alpha2Code: 'BM',
  },
  {
    id: 26,
    code: 'BTN',
    name: 'Bhutan',
    alpha2Code: 'BT',
  },
  {
    id: 27,
    code: 'BOL',
    name: 'Bolivia',
    alpha2Code: 'BO',
  },
  {
    id: 28,
    code: 'BES',
    name: 'Bonaire',
    alpha2Code: 'BQ',
  },
  {
    id: 29,
    code: 'BIH',
    name: 'Bosnia and Herzegovina',
    alpha2Code: 'BA',
  },
  {
    id: 30,
    code: 'BWA',
    name: 'Botswana',
    alpha2Code: 'BW',
  },
  {
    id: 31,
    code: 'BVT',
    name: 'Bouvet Island',
    alpha2Code: 'BV',
  },
  {
    id: 32,
    code: 'BRA',
    name: 'Brazil',
    alpha2Code: 'BR',
  },
  {
    id: 33,
    code: 'IOT',
    name: 'British Indian Ocean Territory',
    alpha2Code: 'IO',
  },
  {
    id: 34,
    code: 'VGB',
    name: 'British Virgin Islands',
    alpha2Code: 'VG',
  },
  {
    id: 35,
    code: 'BRN',
    name: 'Brunei',
    alpha2Code: 'BN',
  },
  {
    id: 36,
    code: 'BGR',
    name: 'Bulgaria',
    alpha2Code: 'BG',
  },
  {
    id: 37,
    code: 'BFA',
    name: 'Burkina Faso',
    alpha2Code: 'BF',
  },
  {
    id: 38,
    code: 'BDI',
    name: 'Burundi',
    alpha2Code: 'BI',
  },
  {
    id: 39,
    code: 'KHM',
    name: 'Cambodia',
    alpha2Code: 'KH',
  },
  {
    id: 40,
    code: 'CMR',
    name: 'Cameroon',
    alpha2Code: 'CM',
  },
  {
    id: 41,
    code: 'CAN',
    name: 'Canada',
    alpha2Code: 'CA',
  },
  {
    id: 42,
    code: 'CPV',
    name: 'Cape Verde',
    alpha2Code: 'CV',
  },
  {
    id: 43,
    code: 'CYM',
    name: 'Cayman Islands',
    alpha2Code: 'KY',
  },
  {
    id: 44,
    code: 'CAF',
    name: 'Central African Republic',
    alpha2Code: 'CF',
  },
  {
    id: 45,
    code: 'TCD',
    name: 'Chad',
    alpha2Code: 'TD',
  },
  {
    id: 46,
    code: 'CHL',
    name: 'Chile',
    alpha2Code: 'CL',
  },
  {
    id: 47,
    code: 'CHN',
    name: 'China',
    alpha2Code: 'CN',
  },
  {
    id: 48,
    code: 'CXR',
    name: 'Christmas Island',
    alpha2Code: 'CX',
  },
  {
    id: 49,
    code: 'CCK',
    name: 'Cocos [Keeling] Islands',
    alpha2Code: 'CC',
  },
  {
    id: 50,
    code: 'COL',
    name: 'Colombia',
    alpha2Code: 'CO',
  },
  {
    id: 51,
    code: 'COM',
    name: 'Comoros',
    alpha2Code: 'KM',
  },
  {
    id: 52,
    code: 'COK',
    name: 'Cook Islands',
    alpha2Code: 'CK',
  },
  {
    id: 53,
    code: 'CRI',
    name: 'Costa Rica',
    alpha2Code: 'CR',
  },
  {
    id: 54,
    code: 'HRV',
    name: 'Croatia',
    alpha2Code: 'HR',
  },
  {
    id: 55,
    code: 'CUB',
    name: 'Cuba',
    alpha2Code: 'CU',
  },
  {
    id: 56,
    code: 'CUW',
    name: 'Curacao',
    alpha2Code: 'CW',
  },
  {
    id: 57,
    code: 'CYP',
    name: 'Cyprus',
    alpha2Code: 'CY',
  },
  {
    id: 58,
    code: 'CZE',
    name: 'Czech Republic',
    alpha2Code: 'CZ',
  },
  {
    id: 59,
    code: 'COD',
    name: 'Democratic Republic of the Congo',
    alpha2Code: 'CD',
  },
  {
    id: 60,
    code: 'DNK',
    name: 'Denmark',
    alpha2Code: 'DK',
  },
  {
    id: 61,
    code: 'DJI',
    name: 'Djibouti',
    alpha2Code: 'DJ',
  },
  {
    id: 62,
    code: 'DMA',
    name: 'Dominica',
    alpha2Code: 'DM',
  },
  {
    id: 63,
    code: 'DOM',
    name: 'Dominican Republic',
    alpha2Code: 'DO',
  },
  {
    id: 64,
    code: 'TLS',
    name: 'East Timor',
    alpha2Code: 'TL',
  },
  {
    id: 65,
    code: 'ECU',
    name: 'Ecuador',
    alpha2Code: 'EC',
  },
  {
    id: 66,
    code: 'EGY',
    name: 'Egypt',
    alpha2Code: 'EG',
  },
  {
    id: 67,
    code: 'SLV',
    name: 'El Salvador',
    alpha2Code: 'SV',
  },
  {
    id: 68,
    code: 'GNQ',
    name: 'Equatorial Guinea',
    alpha2Code: 'GQ',
  },
  {
    id: 69,
    code: 'ERI',
    name: 'Eritrea',
    alpha2Code: 'ER',
  },
  {
    id: 70,
    code: 'EST',
    name: 'Estonia',
    alpha2Code: 'EE',
  },
  {
    id: 71,
    code: 'ETH',
    name: 'Ethiopia',
    alpha2Code: 'ET',
  },
  {
    id: 72,
    code: 'FLK',
    name: 'Falkland Islands',
    alpha2Code: 'FK',
  },
  {
    id: 73,
    code: 'FRO',
    name: 'Faroe Islands',
    alpha2Code: 'FO',
  },
  {
    id: 74,
    code: 'FJI',
    name: 'Fiji',
    alpha2Code: 'FJ',
  },
  {
    id: 75,
    code: 'FIN',
    name: 'Finland',
    alpha2Code: 'FI',
  },
  {
    id: 76,
    code: 'FRA',
    name: 'France',
    alpha2Code: 'FR',
  },
  {
    id: 77,
    code: 'GUF',
    name: 'French Guiana',
    alpha2Code: 'GF',
  },
  {
    id: 78,
    code: 'PYF',
    name: 'French Polynesia',
    alpha2Code: 'PF',
  },
  {
    id: 79,
    code: 'ATF',
    name: 'French Southern Territories',
    alpha2Code: 'TF',
  },
  {
    id: 80,
    code: 'GAB',
    name: 'Gabon',
    alpha2Code: 'GA',
  },
  {
    id: 81,
    code: 'GMB',
    name: 'Gambia',
    alpha2Code: 'GM',
  },
  {
    id: 82,
    code: 'GEO',
    name: 'Georgia',
    alpha2Code: 'GE',
  },
  {
    id: 83,
    code: 'DEU',
    name: 'Germany',
    alpha2Code: 'DE',
  },
  {
    id: 84,
    code: 'GHA',
    name: 'Ghana',
    alpha2Code: 'GH',
  },
  {
    id: 85,
    code: 'GIB',
    name: 'Gibraltar',
    alpha2Code: 'GI',
  },
  {
    id: 86,
    code: 'GRC',
    name: 'Greece',
    alpha2Code: 'GR',
  },
  {
    id: 87,
    code: 'GRL',
    name: 'Greenland',
    alpha2Code: 'GL',
  },
  {
    id: 88,
    code: 'GRD',
    name: 'Grenada',
    alpha2Code: 'GD',
  },
  {
    id: 89,
    code: 'GLP',
    name: 'Guadeloupe',
    alpha2Code: 'GP',
  },
  {
    id: 90,
    code: 'GUM',
    name: 'Guam',
    alpha2Code: 'GU',
  },
  {
    id: 91,
    code: 'GTM',
    name: 'Guatemala',
    alpha2Code: 'GT',
  },
  {
    id: 92,
    code: 'GGY',
    name: 'Guernsey',
    alpha2Code: 'GG',
  },
  {
    id: 93,
    code: 'GIN',
    name: 'Guinea',
    alpha2Code: 'GN',
  },
  {
    id: 94,
    code: 'GNB',
    name: 'Guinea-Bissau',
    alpha2Code: 'GW',
  },
  {
    id: 95,
    code: 'GUY',
    name: 'Guyana',
    alpha2Code: 'GY',
  },
  {
    id: 96,
    code: 'HTI',
    name: 'Haiti',
    alpha2Code: 'HT',
  },
  {
    id: 97,
    code: 'HMD',
    name: 'Heard Island and McDonald Islands',
    alpha2Code: 'HM',
  },
  {
    id: 98,
    code: 'HND',
    name: 'Honduras',
    alpha2Code: 'HN',
  },
  {
    id: 99,
    code: 'HKG',
    name: 'Hong Kong',
    alpha2Code: 'HK',
  },
  {
    id: 100,
    code: 'HUN',
    name: 'Hungary',
    alpha2Code: 'HU',
  },
  {
    id: 101,
    code: 'ISL',
    name: 'Iceland',
    alpha2Code: 'IS',
  },
  {
    id: 102,
    code: 'IND',
    name: 'India',
    alpha2Code: 'IN',
  },
  {
    id: 103,
    code: 'IDN',
    name: 'Indonesia',
    alpha2Code: 'ID',
  },
  {
    id: 104,
    code: 'IRN',
    name: 'Iran',
    alpha2Code: 'IR',
  },
  {
    id: 105,
    code: 'IRQ',
    name: 'Iraq',
    alpha2Code: 'IQ',
  },
  {
    id: 106,
    code: 'IRL',
    name: 'Ireland',
    alpha2Code: 'IE',
  },
  {
    id: 107,
    code: 'IMN',
    name: 'Isle of Man',
    alpha2Code: 'IM',
  },
  {
    id: 108,
    code: 'ISR',
    name: 'Israel',
    alpha2Code: 'IL',
  },
  {
    id: 109,
    code: 'ITA',
    name: 'Italy',
    alpha2Code: 'IT',
  },
  {
    id: 110,
    code: 'CIV',
    name: 'Ivory Coast',
    alpha2Code: 'CI',
  },
  {
    id: 111,
    code: 'JAM',
    name: 'Jamaica',
    alpha2Code: 'JM',
  },
  {
    id: 112,
    code: 'JPN',
    name: 'Japan',
    alpha2Code: 'JP',
  },
  {
    id: 113,
    code: 'JEY',
    name: 'Jersey',
    alpha2Code: 'JE',
  },
  {
    id: 114,
    code: 'JOR',
    name: 'Jordan',
    alpha2Code: 'JO',
  },
  {
    id: 115,
    code: 'KAZ',
    name: 'Kazakhstan',
    alpha2Code: 'KZ',
  },
  {
    id: 116,
    code: 'KEN',
    name: 'Kenya',
    alpha2Code: 'KE',
  },
  {
    id: 117,
    code: 'KIR',
    name: 'Kiribati',
    alpha2Code: 'KI',
  },
  {
    id: 118,
    code: 'XKX',
    name: 'Kosovo',
    alpha2Code: 'XK',
  },
  {
    id: 119,
    code: 'KWT',
    name: 'Kuwait',
    alpha2Code: 'KW',
  },
  {
    id: 120,
    code: 'KGZ',
    name: 'Kyrgyzstan',
    alpha2Code: 'KG',
  },
  {
    id: 121,
    code: 'LAO',
    name: 'Laos',
    alpha2Code: 'LA',
  },
  {
    id: 122,
    code: 'LVA',
    name: 'Latvia',
    alpha2Code: 'LV',
  },
  {
    id: 123,
    code: 'LBN',
    name: 'Lebanon',
    alpha2Code: 'LB',
  },
  {
    id: 124,
    code: 'LSO',
    name: 'Lesotho',
    alpha2Code: 'LS',
  },
  {
    id: 125,
    code: 'LBR',
    name: 'Liberia',
    alpha2Code: 'LR',
  },
  {
    id: 126,
    code: 'LBY',
    name: 'Libya',
    alpha2Code: 'LY',
  },
  {
    id: 127,
    code: 'LIE',
    name: 'Liechtenstein',
    alpha2Code: 'LI',
  },
  {
    id: 128,
    code: 'LTU',
    name: 'Lithuania',
    alpha2Code: 'LT',
  },
  {
    id: 129,
    code: 'LUX',
    name: 'Luxembourg',
    alpha2Code: 'LU',
  },
  {
    id: 130,
    code: 'MAC',
    name: 'Macao',
    alpha2Code: 'MO',
  },
  {
    id: 131,
    code: 'MKD',
    name: 'Macedonia',
    alpha2Code: 'MK',
  },
  {
    id: 132,
    code: 'MDG',
    name: 'Madagascar',
    alpha2Code: 'MG',
  },
  {
    id: 133,
    code: 'MWI',
    name: 'Malawi',
    alpha2Code: 'MW',
  },
  {
    id: 134,
    code: 'MYS',
    name: 'Malaysia',
    alpha2Code: 'MY',
  },
  {
    id: 135,
    code: 'MDV',
    name: 'Maldives',
    alpha2Code: 'MV',
  },
  {
    id: 136,
    code: 'MLI',
    name: 'Mali',
    alpha2Code: 'ML',
  },
  {
    id: 137,
    code: 'MLT',
    name: 'Malta',
    alpha2Code: 'MT',
  },
  {
    id: 138,
    code: 'MHL',
    name: 'Marshall Islands',
    alpha2Code: 'MH',
  },
  {
    id: 139,
    code: 'MTQ',
    name: 'Martinique',
    alpha2Code: 'MQ',
  },
  {
    id: 140,
    code: 'MRT',
    name: 'Mauritania',
    alpha2Code: 'MR',
  },
  {
    id: 141,
    code: 'MUS',
    name: 'Mauritius',
    alpha2Code: 'MU',
  },
  {
    id: 142,
    code: 'MYT',
    name: 'Mayotte',
    alpha2Code: 'YT',
  },
  {
    id: 143,
    code: 'MEX',
    name: 'Mexico',
    alpha2Code: 'MX',
  },
  {
    id: 144,
    code: 'FSM',
    name: 'Micronesia',
    alpha2Code: 'FM',
  },
  {
    id: 145,
    code: 'MDA',
    name: 'Moldova',
    alpha2Code: 'MD',
  },
  {
    id: 146,
    code: 'MCO',
    name: 'Monaco',
    alpha2Code: 'MC',
  },
  {
    id: 147,
    code: 'MNG',
    name: 'Mongolia',
    alpha2Code: 'MN',
  },
  {
    id: 148,
    code: 'MNE',
    name: 'Montenegro',
    alpha2Code: 'ME',
  },
  {
    id: 149,
    code: 'MSR',
    name: 'Montserrat',
    alpha2Code: 'MS',
  },
  {
    id: 150,
    code: 'MAR',
    name: 'Morocco',
    alpha2Code: 'MA',
  },
  {
    id: 151,
    code: 'MOZ',
    name: 'Mozambique',
    alpha2Code: 'MZ',
  },
  {
    id: 152,
    code: 'MMR',
    name: 'Myanmar [Burma]',
    alpha2Code: 'MM',
  },
  {
    id: 153,
    code: 'NAM',
    name: 'Namibia',
    alpha2Code: 'NA',
  },
  {
    id: 154,
    code: 'NRU',
    name: 'Nauru',
    alpha2Code: 'NR',
  },
  {
    id: 155,
    code: 'NPL',
    name: 'Nepal',
    alpha2Code: 'NP',
  },
  {
    id: 156,
    code: 'NLD',
    name: 'Netherlands',
    alpha2Code: 'NL',
  },
  {
    id: 157,
    code: 'NCL',
    name: 'New Caledonia',
    alpha2Code: 'NC',
  },
  {
    id: 158,
    code: 'NZL',
    name: 'New Zealand',
    alpha2Code: 'NZ',
  },
  {
    id: 159,
    code: 'NIC',
    name: 'Nicaragua',
    alpha2Code: 'NI',
  },
  {
    id: 160,
    code: 'NER',
    name: 'Niger',
    alpha2Code: 'NE',
  },
  {
    id: 161,
    code: 'NGA',
    name: 'Nigeria',
    alpha2Code: 'NG',
  },
  {
    id: 162,
    code: 'NIU',
    name: 'Niue',
    alpha2Code: 'NU',
  },
  {
    id: 163,
    code: 'NFK',
    name: 'Norfolk Island',
    alpha2Code: 'NF',
  },
  {
    id: 164,
    code: 'PRK',
    name: 'North Korea',
    alpha2Code: 'KP',
  },
  {
    id: 165,
    code: 'MNP',
    name: 'Northern Mariana Islands',
    alpha2Code: 'MP',
  },
  {
    id: 166,
    code: 'NOR',
    name: 'Norway',
    alpha2Code: 'NO',
  },
  {
    id: 167,
    code: 'OMN',
    name: 'Oman',
    alpha2Code: 'OM',
  },
  {
    id: 168,
    code: 'PAK',
    name: 'Pakistan',
    alpha2Code: 'PK',
  },
  {
    id: 169,
    code: 'PLW',
    name: 'Palau',
    alpha2Code: 'PW',
  },
  {
    id: 170,
    code: 'PSE',
    name: 'Palestine',
    alpha2Code: 'PS',
  },
  {
    id: 171,
    code: 'PAN',
    name: 'Panama',
    alpha2Code: 'PA',
  },
  {
    id: 172,
    code: 'PNG',
    name: 'Papua New Guinea',
    alpha2Code: 'PG',
  },
  {
    id: 173,
    code: 'PRY',
    name: 'Paraguay',
    alpha2Code: 'PY',
  },
  {
    id: 174,
    code: 'PER',
    name: 'Peru',
    alpha2Code: 'PE',
  },
  {
    id: 175,
    code: 'PHL',
    name: 'Philippines',
    alpha2Code: 'PH',
  },
  {
    id: 176,
    code: 'PCN',
    name: 'Pitcairn Islands',
    alpha2Code: 'PN',
  },
  {
    id: 177,
    code: 'POL',
    name: 'Poland',
    alpha2Code: 'PL',
  },
  {
    id: 178,
    code: 'PRT',
    name: 'Portugal',
    alpha2Code: 'PT',
  },
  {
    id: 179,
    code: 'PRI',
    name: 'Puerto Rico',
    alpha2Code: 'PR',
  },
  {
    id: 180,
    code: 'QAT',
    name: 'Qatar',
    alpha2Code: 'QA',
  },
  {
    id: 181,
    code: 'COG',
    name: 'Republic of the Congo',
    alpha2Code: 'CG',
  },
  {
    id: 182,
    code: 'REU',
    name: 'Réunion',
    alpha2Code: 'RE',
  },
  {
    id: 183,
    code: 'ROU',
    name: 'Romania',
    alpha2Code: 'RO',
  },
  {
    id: 184,
    code: 'RUS',
    name: 'Russia',
    alpha2Code: 'RU',
  },
  {
    id: 185,
    code: 'RWA',
    name: 'Rwanda',
    alpha2Code: 'RW',
  },
  {
    id: 186,
    code: 'BLM',
    name: 'Saint Barthélemy',
    alpha2Code: 'BL',
  },
  {
    id: 187,
    code: 'SHN',
    name: 'Saint Helena',
    alpha2Code: 'SH',
  },
  {
    id: 188,
    code: 'KNA',
    name: 'Saint Kitts and Nevis',
    alpha2Code: 'KN',
  },
  {
    id: 189,
    code: 'LCA',
    name: 'Saint Lucia',
    alpha2Code: 'LC',
  },
  {
    id: 190,
    code: 'MAF',
    name: 'Saint Martin',
    alpha2Code: 'MF',
  },
  {
    id: 191,
    code: 'SPM',
    name: 'Saint Pierre and Miquelon',
    alpha2Code: 'PM',
  },
  {
    id: 192,
    code: 'VCT',
    name: 'Saint Vincent and the Grenadines',
    alpha2Code: 'VC',
  },
  {
    id: 193,
    code: 'WSM',
    name: 'Samoa',
    alpha2Code: 'WS',
  },
  {
    id: 194,
    code: 'SMR',
    name: 'San Marino',
    alpha2Code: 'SM',
  },
  {
    id: 195,
    code: 'STP',
    name: 'São Tomé and Príncipe',
    alpha2Code: 'ST',
  },
  {
    id: 196,
    code: 'SAU',
    name: 'Saudi Arabia',
    alpha2Code: 'SA',
  },
  {
    id: 197,
    code: 'SEN',
    name: 'Senegal',
    alpha2Code: 'SN',
  },
  {
    id: 198,
    code: 'SRB',
    name: 'Serbia',
    alpha2Code: 'RS',
  },
  {
    id: 199,
    code: 'SYC',
    name: 'Seychelles',
    alpha2Code: 'SC',
  },
  {
    id: 200,
    code: 'SLE',
    name: 'Sierra Leone',
    alpha2Code: 'SL',
  },
  {
    id: 201,
    code: 'SGP',
    name: 'Singapore',
    alpha2Code: 'SG',
  },
  {
    id: 202,
    code: 'SXM',
    name: 'Sint Maarten',
    alpha2Code: 'SX',
  },
  {
    id: 203,
    code: 'SVK',
    name: 'Slovakia',
    alpha2Code: 'SK',
  },
  {
    id: 204,
    code: 'SVN',
    name: 'Slovenia',
    alpha2Code: 'SI',
  },
  {
    id: 205,
    code: 'SLB',
    name: 'Solomon Islands',
    alpha2Code: 'SB',
  },
  {
    id: 206,
    code: 'SOM',
    name: 'Somalia',
    alpha2Code: 'SO',
  },
  {
    id: 207,
    code: 'ZAF',
    name: 'South Africa',
    alpha2Code: 'ZA',
  },
  {
    id: 208,
    code: 'SGS',
    name: 'South Georgia and the South Sandwich Islands',
    alpha2Code: 'GS',
  },
  {
    id: 209,
    code: 'KOR',
    name: 'South Korea',
    alpha2Code: 'KR',
  },
  {
    id: 210,
    code: 'SSD',
    name: 'South Sudan',
    alpha2Code: 'SS',
  },
  {
    id: 211,
    code: 'ESP',
    name: 'Spain',
    alpha2Code: 'ES',
  },
  {
    id: 212,
    code: 'LKA',
    name: 'Sri Lanka',
    alpha2Code: 'LK',
  },
  {
    id: 213,
    code: 'SDN',
    name: 'Sudan',
    alpha2Code: 'SD',
  },
  {
    id: 214,
    code: 'SUR',
    name: 'Suriname',
    alpha2Code: 'SR',
  },
  {
    id: 215,
    code: 'SJM',
    name: 'Svalbard and Jan Mayen',
    alpha2Code: 'SJ',
  },
  {
    id: 216,
    code: 'SWZ',
    name: 'Swaziland',
    alpha2Code: 'SZ',
  },
  {
    id: 217,
    code: 'SWE',
    name: 'Sweden',
    alpha2Code: 'SE',
  },
  {
    id: 218,
    code: 'CHE',
    name: 'Switzerland',
    alpha2Code: 'CH',
  },
  {
    id: 219,
    code: 'SYR',
    name: 'Syria',
    alpha2Code: 'SY',
  },
  {
    id: 220,
    code: 'TWN',
    name: 'Taiwan',
    alpha2Code: 'TW',
  },
  {
    id: 221,
    code: 'TJK',
    name: 'Tajikistan',
    alpha2Code: 'TJ',
  },
  {
    id: 222,
    code: 'TZA',
    name: 'Tanzania',
    alpha2Code: 'TZ',
  },
  {
    id: 223,
    code: 'THA',
    name: 'Thailand',
    alpha2Code: 'TH',
  },
  {
    id: 224,
    code: 'TGO',
    name: 'Togo',
    alpha2Code: 'TG',
  },
  {
    id: 225,
    code: 'TKL',
    name: 'Tokelau',
    alpha2Code: 'TK',
  },
  {
    id: 226,
    code: 'TON',
    name: 'Tonga',
    alpha2Code: 'TO',
  },
  {
    id: 227,
    code: 'TTO',
    name: 'Trinidad and Tobago',
    alpha2Code: 'TT',
  },
  {
    id: 228,
    code: 'TUN',
    name: 'Tunisia',
    alpha2Code: 'TN',
  },
  {
    id: 229,
    code: 'TUR',
    name: 'Turkey',
    alpha2Code: 'TR',
  },
  {
    id: 230,
    code: 'TKM',
    name: 'Turkmenistan',
    alpha2Code: 'TM',
  },
  {
    id: 231,
    code: 'TCA',
    name: 'Turks and Caicos Islands',
    alpha2Code: 'TC',
  },
  {
    id: 232,
    code: 'TUV',
    name: 'Tuvalu',
    alpha2Code: 'TV',
  },
  {
    id: 233,
    code: 'UMI',
    name: 'U.S. Minor Outlying Islands',
    alpha2Code: 'UM',
  },
  {
    id: 234,
    code: 'VIR',
    name: 'U.S. Virgin Islands',
    alpha2Code: 'VI',
  },
  {
    id: 235,
    code: 'UGA',
    name: 'Uganda',
    alpha2Code: 'UG',
  },
  {
    id: 236,
    code: 'UKR',
    name: 'Ukraine',
    alpha2Code: 'UA',
  },
  {
    id: 237,
    code: 'ARE',
    name: 'United Arab Emirates',
    alpha2Code: 'AE',
  },
  {
    id: 238,
    code: 'GBR',
    name: 'United Kingdom',
    alpha2Code: 'GB',
  },
  {
    id: 239,
    code: 'USA',
    name: 'United States',
    alpha2Code: 'US',
  },
  {
    id: 240,
    code: 'URY',
    name: 'Uruguay',
    alpha2Code: 'UY',
  },
  {
    id: 241,
    code: 'UZB',
    name: 'Uzbekistan',
    alpha2Code: 'UZ',
  },
  {
    id: 242,
    code: 'VUT',
    name: 'Vanuatu',
    alpha2Code: 'VU',
  },
  {
    id: 243,
    code: 'VAT',
    name: 'Vatican City',
    alpha2Code: 'VA',
  },
  {
    id: 244,
    code: 'VEN',
    name: 'Venezuela',
    alpha2Code: 'VE',
  },
  {
    id: 245,
    code: 'VNM',
    name: 'Vietnam',
    alpha2Code: 'VN',
  },
  {
    id: 246,
    code: 'WLF',
    name: 'Wallis and Futuna',
    alpha2Code: 'WF',
  },
  {
    id: 247,
    code: 'ESH',
    name: 'Western Sahara',
    alpha2Code: 'EH',
  },
  {
    id: 248,
    code: 'YEM',
    name: 'Yemen',
    alpha2Code: 'YE',
  },
  {
    id: 249,
    code: 'ZMB',
    name: 'Zambia',
    alpha2Code: 'ZM',
  },
  {
    id: 250,
    code: 'ZWE',
    name: 'Zimbabwe',
    alpha2Code: 'ZW',
  },
]
